### ISSUE TITLE
odom and base link

### ISSUE THREAD

**Issue by adnanhd** [adnanhd/metu-rover#18]
when I tried to execute `rosrun metu_navigation run.sh` in terminal
I got the error as below

Could not get transform from odom to base_link after 0.200000 seconds (for stamp=28.057000)! Error="Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after 0.201 timeout was 0.2."

Can someone help?

**Comment by al3v** [comment]
You can fix it by going inside the `leo_gazebo/config/controller.yaml` file and switch "- enable odom tf" from false to true

**Comment by adnanhd** [comment]
Thanks, @al3v. It worked for me
